//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_blog.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbility
    {
        public int Id { get; set; }
        public string ability { get; set; }
        public Nullable<byte> rate { get; set; }
    }
}
